all:
  type: all
  title: Home
  icon: newspaper
  link: /
home:
  type: home
  title: Home
  icon: newspaper
  link: /
java:
  type: java
  title: Java
  icon: coffee
  link: /posts/java
jpa:
  type: jpa
  title: JPA
  icon: database
  link: /posts/java/jpa
spring:
  type: spring
  title: Spring
  icon: sprout
  link: /posts/java/spring
javascript:
  type: javascript
  title: JavaScript
  icon: braces
  link: /posts/javascript
react:
  type: react
  title: react
  icon: atom
  link: /posts/javascript/react
angular:
  type: angular
  title: Angular
  icon: triangle
  link: /posts/javascript/angular
angularjs:
  type: angularjs
  title: AngularJs
  icon: triangle
  link: /posts/javascript/angularjs
typescript:
  type: typescript
  title: Typescript
  icon: file-code-2
  link: /posts/typescript
Design-pattern:
  type: Design-pattern
  title: Design Patterns
  icon: puzzle
  link: /posts/javascript/design-patterns
