all:
  type: all
  title: Home
  icon: far fa-newspaper
  link: /
home:
  type: home
  title: Home
  icon: far fa-newspaper
  link: /  
java:
  type: java
  title: Java
  icon: fab fa-java
  link: /posts/java
jpa:
  type: jpa
  title: JPA
  icon: fas fa-cube
  link: /posts/java/jpa
spring:
  type: spring
  title: Spring
  icon: fas fa-seedling
  link: /posts/java/spring
javascript:
  type: javascript
  title: JavaScript
  icon: fab fa-js-square
  link: /posts/javascript
angular:
  type: angular
  title: Angular
  icon: fab fa-angular
  link: /posts/javascript/angular
angularjs:
  type: angularjs
  title: AngularJs
  icon: fab fa-angular
  link: /posts/javascript/angularjs
typescript:
  type: typescript
  title: Typescript
  icon: fab fa-js-square
  link: /posts/typescript
Design-pattern:
  type: Design-pattern
  title: Design Patterns
  icon: fas fa-paint-roller
  link: /posts/javascript/design-patterns


